# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V86FqCZxxCCZIviw6Qt-rYVdo7gaM3h1
"""

import pandas as pd
prices = [2999,3444,5666,7777,8888]
products = ["wireless Earbuds","smartphone","laptop","smartwatch","Bluetooth"]
product_prices = pd.Series(prices,index=products) # we use series whn its in key value pairs
print(product_prices)

print("Mean:",product_prices.mean())
print("Sum:",product_prices.sum())
print("Max:",product_prices.max())
print("Min:",product_prices.min())

print(product_prices.head(2)) #gives the starting values
print(product_prices.tail(1)) #gives the end values

#map is used to update each and every elements .. apply is used for more complex
print(product_prices.apply(lambda x: f'₹{x+(x*0.18)}'))
print(product_prices.map(lambda x: f'₹{x}.00'))

print(product_prices.sort_values())
print(product_prices.sort_index())
print(product_prices.sort_index(ascending=False))
print(product_prices.value_counts())

#keys=>column rows=> values
data = {
  "Product":["wireless Earbuds","smartphone","laptop","smartwatch","Bluetooth"],
  "Brand":["SoundMax","TechNova","Apple","TimeTracker","Bytecore"],
  "Price":[2999,3444,5666,7777,8888],
  "Stock":[50,30,20,40,60],
  "BestSeller":[True,False,False,True,True]
}
df = pd.DataFrame(data)
print(df)

from google.colab import files
import pandas as pd

uploaded = files.upload()
df = pd.read_excel("product_50_rows.xlsx.xlsx")
print(df)

print(df.shape)
print(df.columns)
print(df.info())

print(df.head(5))
print(df.tail(5))

print(df.iloc[0]) #accessing row
print(df.iloc[1])
print(df["Product"]) #accessing column
print(df["Stock"])  #accessing column

print(df)
print(df.loc[2, "Brand"])
print(df.loc[3, "Product"])
print(df.loc[12, "Stock"])

print(df.iloc[4,0])
print(df.iloc[2,1])
print(df.iloc[3,3])

df_dropped = df.drop(columns=["Stock"])
#df.drop(columns=["Stock"],inplace=True)
print(df_dropped)

df_renamed = df.rename(columns={"Price":"Cost"})
print(df_renamed)
#df.rename(columns={"Product":"Product name",inplace = True})

print(df)
print(df.loc[df['BestSeller']==True])   #df.loc[df["...."]] for filtering
print(df.loc[df['Stock']<40])
print(df.loc[df['Price']<10000])

#grouping and sumarise the output
df_grouped = df.groupby("Brand").agg({"Price":"mean","Stock":"sum"})
print(df_grouped)
grouped = df.groupby("Brand").agg({"Price":["mean","max","min","sum"]})
print(grouped)
grouped = df.groupby("Brand")["Price"].mean()
print(grouped)

data2 = {
    "Brand":["SoundMax","TechNova","ByteCore","TimeTracker","EchoBoom"],
    "Rating":[4.2,4.5,4.0,4.1,3.9],
    "dicount":[28,40,16,5,8]
}
df_ratings = pd.DataFrame(data2)
print(df_ratings)

df_merged = df.merge(df_ratings,on="Brand")
print("Merged DataFrame(Adding Ratings):\n",df_merged)

new_data ={
    "Product":["Tablet"],
    "Brand":["SmartWare"],
    "Price":[12999],
    "Stock":[25],
    "BestSeller":[True]
}
df_new = pd.DataFrame(new_data)
print(df_new)

df_concat = pd.concat([df,df_new],ignore_index=True)
print("Concatenated DataFrame:\n",df_concat)